
import type { Metadata } from "next";
import { Noto_Serif_Yezidi } from 'next/font/google';
import "./globals.css";

const notoSerifYezidi = Noto_Serif_Yezidi({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-noto-serif',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSerifYezidi.variable} font-body antialiased`}>
        {children}
      </body>
    </html>
  );
}
